# -*- coding: utf-8 -*-
"""Marketing ROI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6BwUkTwvFoTIG-Us84z1EIJmfQsLVP6
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pickle
import warnings
from datetime import datetime, timedelta
import random

warnings.filterwarnings('ignore')

# ================================================
# PAGE CONFIGURATION
# ================================================
st.set_page_config(
    page_title="Campaign Performance Predictor",
    page_icon="📢",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ================================================
# CUSTOM CSS FOR MODERN LOOK
# ================================================
st.markdown("""
    <style>
    /* Modern gradient headers */
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 20px;
        color: white;
        text-align: center;
        margin-bottom: 2rem;
        box-shadow: 0 10px 30px rgba(0,0,0,0.2);
    }

    /* Metric cards */
    .metric-card {
        background: white;
        padding: 1.5rem;
        border-radius: 15px;
        box-shadow: 0 5px 20px rgba(0,0,0,0.1);
        text-align: center;
        transition: transform 0.3s;
    }
    .metric-card:hover {
        transform: translateY(-5px);
    }

    /* Channel cards */
    .channel-card {
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        padding: 1rem;
        border-radius: 10px;
        margin: 0.5rem 0;
        border-left: 5px solid #667eea;
    }

    /* Success metrics */
    .success-metric {
        font-size: 2rem;
        font-weight: bold;
        color: #27ae60;
    }
    .warning-metric {
        font-size: 2rem;
        font-weight: bold;
        color: #e67e22;
    }
    .danger-metric {
        font-size: 2rem;
        font-weight: bold;
        color: #e74c3c;
    }

    /* Buttons */
    .stButton > button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        font-size: 1.2rem;
        font-weight: bold;
        border: none;
        padding: 0.75rem 2rem;
        border-radius: 10px;
        transition: all 0.3s;
        width: 100%;
    }
    .stButton > button:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
    }

    /* Tabs styling */
    .stTabs [data-baseweb="tab-list"] {
        gap: 2rem;
        background-color: #f8f9fa;
        padding: 1rem;
        border-radius: 10px;
    }
    .stTabs [data-baseweb="tab"] {
        font-size: 1.1rem;
        font-weight: 600;
    }
    </style>
""", unsafe_allow_html=True)

# ================================================
# HEADER SECTION
# ================================================
st.markdown("""
    <div class="main-header">
        <h1>📢 Campaign Performance Prediction System</h1>
        <p style="font-size: 1.2rem;">Predict • Optimize • Maximize ROI</p>
    </div>
""", unsafe_allow_html=True)

# ================================================
# SIDEBAR - CAMPAIGN INPUTS
# ================================================
with st.sidebar:
    st.markdown("### 🎯 Campaign Configuration")
    st.markdown("---")

    # Campaign Basics
    st.markdown("#### 📋 Campaign Details")
    campaign_name = st.text_input("Campaign Name", "Summer Sale 2024")

    col1, col2 = st.columns(2)
    with col1:
        campaign_goal = st.selectbox(
            "Campaign Goal",
            ["Brand Awareness", "Lead Generation", "Conversion", "Retention", "Upselling", "New Product Launch"]
        )
    with col2:
        target_audience = st.selectbox(
            "Target Audience",
            ["Millennials", "Gen Z", "Gen X", "Baby Boomers", "All Ages", "Professionals", "Students"]
        )

    # Channel Selection
    st.markdown("#### 📱 Marketing Channels")
    channels = st.multiselect(
        "Select Channels (max 3)",
        ["Email", "Social Media", "Search Ads", "Display Ads", "TV", "Radio", "Print", "Influencer", "SMS", "Push Notifications"],
        default=["Email", "Social Media"],
        max_selections=3
    )

    # Budget & Duration
    st.markdown("#### 💰 Budget & Timeline")
    col3, col4 = st.columns(2)
    with col3:
        budget = st.number_input("Budget ($", min_value=1000, max_value=1000000, value=50000, step=5000)
    with col4:
        duration = st.slider("Duration (days)", 1, 90, 30)

    # Location & Language
    st.markdown("#### 🌍 Geographic Targeting")
    col5, col6 = st.columns(2)
    with col5:
        location = st.selectbox(
            "Primary Location",
            ["North America", "Europe", "Asia", "South America", "Africa", "Australia", "Global"]
        )
    with col6:
        language = st.selectbox(
            "Language",
            ["English", "Spanish", "French", "German", "Mandarin", "Japanese", "Multiple"]
        )

    # Customer Segment
    st.markdown("#### 🎯 Customer Segment")
    segment = st.selectbox(
        "Target Segment",
        ["New Customers", "Existing Customers", "High Value", "At Risk", "Inactive", "All Customers"]
    )

    st.markdown("---")
    predict_button = st.button("🚀 **Predict Campaign Performance**", use_container_width=True)

# ================================================
# MAIN CONTENT AREA - TABS FOR DIFFERENT ANALYSES
# ================================================
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Performance Prediction",
    "📈 Channel Analysis",
    "🎯 What-If Simulator",
    "🔍 Feature Importance",
    "📋 Historical Benchmarks"
])

# ================================================
# TAB 1: PERFORMANCE PREDICTION
# ================================================
with tab1:
    if predict_button:
        # Simulate predictions (replace with actual model predictions)
        with st.spinner("Analyzing campaign data..."):
            # Simulated predictions based on inputs
            roi_pred = round(random.uniform(120, 350), 2)
            conv_rate = round(random.uniform(2.5, 8.5), 2)
            engagement = round(random.uniform(65, 95), 1)
            clicks = int(random.uniform(5000, 50000))
            impressions = int(clicks * random.uniform(10, 30))

            # Success classification
            success_status = "High Success" if roi_pred > 200 else "Moderate Success" if roi_pred > 150 else "Low Success"
            success_color = "success-metric" if roi_pred > 200 else "warning-metric" if roi_pred > 150 else "danger-metric"

            # Display predictions in modern cards
            st.markdown("### 📊 Predicted Campaign Performance")

            # Top metrics row
            col1, col2, col3, col4 = st.columns(4)

            with col1:
                st.markdown(f"""
                    <div class="metric-card">
                        <h3>ROI</h3>
                        <div class="{success_color}">{roi_pred}%</div>
                        <p>vs target: 150%</p>
                    </div>
                """, unsafe_allow_html=True)

            with col2:
                st.markdown(f"""
                    <div class="metric-card">
                        <h3>Conversion Rate</h3>
                        <div class="success-metric">{conv_rate}%</div>
                        <p>Industry avg: 3.2%</p>
                    </div>
                """, unsafe_allow_html=True)

            with col3:
                st.markdown(f"""
                    <div class="metric-card">
                        <h3>Engagement Score</h3>
                        <div class="success-metric">{engagement}</div>
                        <p>out of 100</p>
                    </div>
                """, unsafe_allow_html=True)

            with col4:
                st.markdown(f"""
                    <div class="metric-card">
                        <h3>Expected Reach</h3>
                        <div class="warning-metric">{impressions:,}</div>
                        <p>impressions</p>
                    </div>
                """, unsafe_allow_html=True)

            # Performance gauge chart
            st.markdown("### 📈 Performance Scorecard")

            # Create gauge for overall performance
            fig = make_subplots(
                rows=1, cols=3,
                subplot_titles=('ROI Target', 'Conversion Goal', 'Engagement Goal'),
                specs=[[{'type': 'indicator'}, {'type': 'indicator'}, {'type': 'indicator'}]]
            )

            fig.add_trace(go.Indicator(
                mode = "gauge+number+delta",
                value = roi_pred,
                delta = {'reference': 150},
                gauge = {
                    'axis': {'range': [None, 300]},
                    'bar': {'color': "#667eea"},
                    'steps': [
                        {'range': [0, 150], 'color': "#ffcccc"},
                        {'range': [150, 300], 'color': "#ccffcc"}],
                    'threshold': {
                        'line': {'color': "red", 'width': 4},
                        'thickness': 0.75,
                        'value': 150}}),
                row=1, col=1)

            fig.add_trace(go.Indicator(
                mode = "gauge+number+delta",
                value = conv_rate,
                delta = {'reference': 3.2},
                gauge = {
                    'axis': {'range': [None, 10]},
                    'bar': {'color': "#764ba2"}}),
                row=1, col=2)

            fig.add_trace(go.Indicator(
                mode = "gauge+number+delta",
                value = engagement,
                delta = {'reference': 70},
                gauge = {
                    'axis': {'range': [None, 100]},
                    'bar': {'color': "#27ae60"}}),
                row=1, col=3)

            fig.update_layout(height=300, showlegend=False)
            st.plotly_chart(fig, width='stretch')

            # Detailed breakdown
            st.markdown("### 🔍 Detailed Analysis")

            col1, col2 = st.columns(2)

            with col1:
                st.markdown("#### 💡 Key Insights")
                insights = [
                    f"✅ {channels[0] if channels else 'Email'} shows highest potential for {target_audience}",
                    f"⚠️ Budget of ${budget:,} is {'optimal' if budget < 100000 else 'above average'} for {duration} days",
                    f"📊 Expected CTR: {(clicks/impressions*100):.2f}%",
                    f"💰 Cost per acquisition: ${(budget/(clicks*conv_rate/100)):.2f}" if clicks > 0 else "💰 CPA: N/A"
                ]
                for insight in insights:
                    st.info(insight)

            with col2:
                st.markdown("#### 🎯 Recommendations")
                recommendations = [
                    f"📧 Allocate 60% budget to {channels[0] if channels else 'Email'}",
                    f"📱 Consider A/B testing on {channels[1] if len(channels) > 1 else 'Social Media'}",
                    f"⏰ Optimal campaign start: Next Monday",
                    f"🎨 Focus on {campaign_goal} messaging for {segment}"
                ]
                for rec in recommendations:
                    st.success(rec)
    else:
        st.info("👈 Configure your campaign in the sidebar and click 'Predict Campaign Performance' to see results")
        # Show sample visualization
        st.markdown("### 📊 Sample Campaign Analytics")
        # Create sample chart
        sample_data = pd.DataFrame({
            'Channel': ['Email', 'Social', 'Search', 'Display', 'TV'],
            'Avg_ROI': [280, 210, 190, 120, 80],
            'Success_Rate': [0.85, 0.75, 0.65, 0.45, 0.30]
        })
        fig = px.bar(sample_data, x='Channel', y='Avg_ROI', color='Success_Rate',
                    title='Average ROI by Channel (Historical)',
                    color_continuous_scale='Viridis')
        st.plotly_chart(fig, width='stretch')

# ================================================
# TAB 2: CHANNEL ANALYSIS
# ================================================
with tab2:
    st.markdown("### 📊 Channel Performance Analysis")

    # Channel performance data
    channel_data = pd.DataFrame({
        'Channel': ['Email', 'Social Media', 'Search Ads', 'Display Ads', 'TV', 'Radio', 'Influencer'],
        'Avg_ROI': [280, 210, 190, 120, 80, 95, 230],
        'Engagement': [75, 88, 70, 65, 55, 50, 92],
        'Cost_per_click': [0.5, 1.2, 2.1, 1.8, 5.5, 3.2, 4.5],
        'Conversion_Rate': [4.2, 3.8, 3.5, 2.1, 1.2, 1.5, 4.5]
    })

    col1, col2 = st.columns(2)

    with col1:
        # ROI by channel
        fig1 = px.bar(channel_data.sort_values('Avg_ROI', ascending=True),
                     x='Avg_ROI', y='Channel',
                     orientation='h',
                     title='Average ROI by Channel',
                     color='Avg_ROI',
                     color_continuous_scale='Viridis')
        st.plotly_chart(fig1, width='stretch')

    with col2:
        # Bubble chart
        fig2 = px.scatter(channel_data, x='Cost_per_click', y='Avg_ROI',
                         size='Engagement', color='Channel',
                         title='Channel Efficiency Matrix',
                         labels={'Cost_per_click': 'Cost per Click ($)', 'Avg_ROI': 'ROI (%)'})
        st.plotly_chart(fig2, width='stretch')

    # Segment-specific recommendations
    st.markdown("### 🎯 Segment-Specific Channel Recommendations")

    segment_recommendations = pd.DataFrame({
        'Customer Segment': ['Millennials', 'Gen Z', 'Gen X', 'Baby Boomers', 'Professionals'],
        'Top Channel': ['Social Media', 'Influencer', 'Email', 'TV', 'LinkedIn'],
        'Expected ROI': ['220-280%', '200-260%', '180-240%', '120-180%', '200-250%'],
        'Best Time': ['Evenings', 'Late Night', 'Morning', 'Daytime', 'Business Hours']
    })

    st.dataframe(segment_recommendations, width='stretch')

# ================================================
# TAB 3: WHAT-IF SIMULATOR
# ================================================
with tab3:
    st.markdown("### 🔮 What-If Simulation")
    st.markdown("Adjust parameters to see how they impact predicted ROI")

    col1, col2, col3 = st.columns(3)

    with col1:
        sim_budget = st.slider("Budget ($", 1000, 500000, 50000, step=5000, key="sim_budget")
    with col2:
        sim_duration = st.slider("Duration (days)", 1, 60, 30, key="sim_duration")
    with col3:
        sim_channels = st.multiselect("Channels",
                                     ["Email", "Social", "Search", "Display", "TV"],
                                     default=["Email", "Social"], key="sim_channels")

    if st.button("Run Simulation", key="sim_button"):
        # Simulate ROI based on parameters
        base_roi = 150
        channel_boost = len(sim_channels) * 20
        budget_factor = min(sim_budget / 50000, 2) * 30
        duration_factor = min(sim_duration / 30, 1.5) * 20

        simulated_roi = base_roi + channel_boost + budget_factor + duration_factor

        # Show results
        st.markdown("### 📊 Simulation Results")

        col_a, col_b, col_c = st.columns(3)
        col_a.metric("Predicted ROI", f"{simulated_roi:.1f}%",
                    f"{simulated_roi - base_roi:.1f}% vs baseline")
        col_b.metric("Confidence Score", "85%", "High")
        col_c.metric("Risk Level", "Medium", "Manageable")

        # ROI breakdown
        breakdown = pd.DataFrame({
            'Factor': ['Base ROI', 'Channel Mix', 'Budget Impact', 'Duration Impact'],
            'Contribution': [base_roi, channel_boost, budget_factor, duration_factor]
        })

        fig = px.pie(breakdown, values='Contribution', names='Factor',
                    title='ROI Contribution Breakdown')
        st.plotly_chart(fig, width='stretch')

# ================================================
# TAB 4: FEATURE IMPORTANCE
# ================================================
with tab4:
    st.markdown("### 🔍 What Drives Campaign Success?")

    # Feature importance data (from your model)
    feature_importance = pd.DataFrame({
        'Feature': ['Channel_Used', 'Customer_Segment', 'Budget', 'Duration',
                   'Campaign_Goal', 'Location', 'Seasonality', 'Language',
                   'Target_Audience', 'Previous_ROI'],
        'Importance': [0.25, 0.18, 0.15, 0.12, 0.10, 0.08, 0.05, 0.04, 0.02, 0.01]
    })

    col1, col2 = st.columns([1.5, 1])

    with col1:
        fig = px.bar(feature_importance.sort_values('Importance', ascending=True),
                    x='Importance', y='Feature',
                    orientation='h',
                    title='Feature Importance in Predicting Campaign Success',
                    color='Importance',
                    color_continuous_scale='Viridis')
        st.plotly_chart(fig, width='stretch')

    with col2:
        st.markdown("#### 📝 Key Takeaways")
        st.info("🎯 **Channel selection** is the most critical factor (25% impact)")
        st.info("👥 **Customer segment** targeting explains 18% of success")
        st.info("💰 **Budget allocation** accounts for 15% of performance")
        st.info("⏱️ **Campaign duration** matters (12% impact)")
        st.info("📍 **Location** affects 8% of campaign success")

        st.markdown("#### 💡 Optimization Tips")
        st.success("Focus on Channel-Segment fit for maximum ROI")
        st.success("Optimize budget based on historical performance")
        st.success("Test different durations for each channel")

# ================================================
# TAB 5: HISTORICAL BENCHMARKS
# ================================================
with tab5:
    st.markdown("### 📊 Historical Campaign Benchmarks")

    # Sample historical data
    historical_data = pd.DataFrame({
        'Campaign': ['Summer Sale 2023', 'Winter Promo', 'Spring Launch', 'Holiday Special',
                    'Black Friday', 'New Year Campaign'],
        'Channel': ['Email+Social', 'TV+Radio', 'Search+Display', 'Social+Influencer', 'Multi-channel', 'Email'],
        'ROI': [245, 112, 178, 298, 320, 156],
        'Conversion': [4.2, 1.8, 3.1, 5.2, 5.8, 2.9],
        'Segment': ['Millennials', 'Gen X', 'All', 'Gen Z', 'All', 'Existing']
    })

    col1, col2 = st.columns(2)

    with col1:
        # Top performing campaigns
        st.markdown("#### 🏆 Top 5 Performing Campaigns")
        top_campaigns = historical_data.nlargest(5, 'ROI')[['Campaign', 'Channel', 'ROI', 'Conversion']]
        st.dataframe(top_campaigns, width='stretch')

    with col2:
        # Average metrics by channel
        avg_by_channel = historical_data.groupby('Channel')['ROI'].mean().reset_index()
        fig = px.pie(avg_by_channel, values='ROI', names='Channel',
                    title='ROI Distribution by Channel')
        st.plotly_chart(fig, width='stretch')

    # Benchmark table
    st.markdown("#### 📈 Industry Benchmarks")
    benchmarks = pd.DataFrame({
        'Metric': ['Average ROI', 'Top Quartile ROI', 'Average Conversion Rate',
                  'Average CTR', 'Cost per Lead', 'Engagement Rate'],
        'Your Industry': ['150%', '280%', '3.2%', '2.1%', '$45', '4.5%'],
        'Best in Class': ['320%', '450%', '7.5%', '5.8%', '$22', '12%']
    })
    st.dataframe(benchmarks, width='stretch')

# ================================================
# FOOTER
# ================================================
st.markdown("---")
st.markdown("""
    <div style="text-align: center; color: #666; padding: 20px;">
        <p>📢 Campaign Performance Prediction System • Powered by Machine Learning</p>
        <p>Built with ❤️ using Streamlit • v2.0</p>
    </div>
""", unsafe_allow_html=True)